from subprocess import call
print("---------------------+ INITIALISATION +---------------------")
print("------------------------------------------------------------")
print("###################### Adding IPv4 address for WFS Network")
call(["sudo", "ip", "address", "add", "192.168.3.201/24", "dev", "eth0"])
print("------------------------------------------------------------")
print("###################### Configuration of lowpan settings ")
call(["sudo", "../../opt/src/wpan-raspbian/usr/local/sbin/create_lowpan", "16", "0x2804"])
print("------------------------------------------------------------")
print("###################### Adding Unique Local Adress (IPv6 Address) for local network")
call(["sudo", "ip", "addr", "add", "fd9a:620d:c050:0:1ac0:ffee:1ac0:ffee/64", "dev", "lowpan0"])
print(". added fd9a:620d:c050:0:1ac0:ffee:1ac0:ffee/64")
print("------------------------------------------------------------")
print("###################### Start radvd for Router Advertisement")
call(["sudo", "radvd", "-d", "5", "-m", "stderr", "-n"])
